### ISSUE TITLE
Titus-executor build problems

### ISSUE THREAD

**Issue by tguvdamm** [Netflix/titus-executor#193]
Hi

I'm a master student researching container orchestration software stacks. 
I'm having troubles building the titus-executor deb file. 
After following instructions on the [executor wiki](https://github.com/Netflix/titus-executor)  
`sudo -E PATH=${PATH} make builder all` fails at the local-test check. I've included the [test-local.log](https://github.com/Netflix/titus-executor/files/2545125/test-local.log).

`make build-standalone` results in errors when executing gox commands:
````sh-session
tguvdamm@n104-05:~/go/src/github.com/Netflix/titus-executor$ make build-standalone
git submodule update --init --recursive
hack/builder/titus-executor-builder.sh
~/go/src/github.com/Netflix/titus-executor ~/go/src/github.com/Netflix/titus-executor
flag provided but not defined: -gcflags
````

The solution [stated by logicbomb](https://github.com/Netflix/titus-executor/issues/93#issuecomment-384496612) does not work for me, the same test fails.

So in the end, the $GOPATH/src/github.com/Netflix/titus-executor/build/distributions/titus-executor_latest.deb file does not exitst.
Any ideas as to why building fails? 

Maybe some relevant extra info:
-I had to manually clone the titus-executor repo and tini submodule, go was denied access, even when elevated as sudo
-I had to install gox via apt
-system info: Ubuntu 18.04/amd64, the deployment page states Titus Agents are currently run on Trusty, but compiling the code should be fine on any platform I guess.

Thanks

**Comment by tguvdamm** [comment]
I managed to continue the execution of `make build-standalone`, the version supplied for gox by apt isn't the most recent version. 
Then, I had to change an included file from attr/xattr.h to sys/xattr.h, as the former one is deprecated.
However, now the code stops building at the following lines: 

````sh-session
In file included from /usr/include/libnl3/netlink/socket.h:16:0,
                 from /users/tguvdamm/go/src/github.com/Netflix/titus-executor/inject-metadataproxy/titus-inject-metadataproxy.c:20:
/usr/include/libnl3/netlink/handlers.h:51:15: error: ‘struct nlmsgerr’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
        struct nlmsgerr *nlerr, void *arg);
               ^~~~~~~~
/usr/include/libnl3/netlink/handlers.h:50:43: error: ‘struct sockaddr_nl’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 typedef int (*nl_recvmsg_err_cb_t)(struct sockaddr_nl *nla,
                                           ^~~~~~~~~~~
/usr/include/libnl3/netlink/handlers.h:135:18: error: ‘struct sockaddr_nl’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
           struct sockaddr_nl *,
                  ^~~~~~~~~~~
cc1: all warnings being treated as errors
````

This does not seems like a version mismatch anymore.

**Comment by sargun** [comment]
Sorry, I didn't see your response. What version of libnl are you compiling with? Also, what version of the operating system are you compiling with? 

The code has to be compiled on Xenial, AFAIK. And the libnl version in Xenial is a little old. You can see here: https://github.com/Netflix/titus-executor/blob/master/hack/builder/Dockerfile -- we pull in a newer version of libnl during compilation.

**Comment by sargun** [comment]
Huh. That's really interesting. Your libc kernel headers are not up to date. Can you tell me what version of "libc6-dev" you have?

**Comment by tguvdamm** [comment]
I updated and upgraded apt before starting installing Titus:
`libc6-dev is already the newest version (2.23-0ubuntu10).`

**Comment by sargun** [comment]
Maybe try to build in Ubuntu bionic?

Sent from my iPhone

On Nov 16, 2018, at 09:08, tguvdamm <notifications@github.com> wrote:

I updated and upgraded apt before starting installing Titus:
libc6-dev is already the newest version (2.23-0ubuntu10).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Netflix/titus-executor/issues/193#issuecomment-439460777>,
or mute the thread

**Comment by sargun** [comment]
Huh, that's weird. How did you install the new libnl package?

**Comment by tguvdamm** [comment]
I copied the instructions (approximately) from the Dockerfile and executed those:

````bash
wget https://github.com/thom311/libnl/releases/download/libnl3_4_0/libnl-3.4.0.tar.gz
tar -xvzf libnl-3.4.0.tar.gz
cd libnl-3.4.0
sudo ./configure
sudo make
sudo make install

````

**Comment by alekar** [comment]
Closing this issue since t has been inactive for over an year.
