### ISSUE TITLE
[Q] Can not compile titus-executor

### ISSUE THREAD

**Issue by angelbarrera92** [Netflix/titus-executor#93]
Hi!
Thank you for releasing the source code for titus. I really want to try it. 

I'm following your [published instructions](https://github.com/Netflix/titus-executor/blob/master/README.md#building) and you're failing me in the build step. 

Attached is the log output
[log.txt](https://github.com/Netflix/titus-executor/files/1934253/log.txt)

There seems to be some problem with some go dependency (govendor and go-junir?)

```
| tee checkstyle-result.xml
go get github.com/kardianos/govendor
bash: govendor: no se encontró la orden
go get github.com/jstemmer/go-junit-report
bash: govendor: no se encontró la orden
govendor test -v -parallel 32 +local \
| tee /dev/stderr \
| tee test-local.log \
| go-junit-report > test.xml
bash: govendor: no se encontró la orden
bash: govendor: no se encontró la orden
bash: línea 3: go-junit-report: no se encontró la orden
make: *** [Makefile:57: test-local] Error 127
```

Thanks

**Comment by logicbomb** [comment]
I was able to compile and build the executor by following these steps (caveats follow)

0. Download and build the metalinter & govendor packages per the docs
1. Create the GOPATH env var (i'm not 100% sure this is necessary)
2. Download go-junit-report 
```
go get -u github.com/jstemmer/go-junit-report
cd $GOPATH/github.com/jstemmer/go-junit-report
go build
```
3. Compile by specifying the path to govendor & go-junit-report
```
PATH="$GOPATH/src/github.com/jstemmer/go-junit-report:$GOPATH/src/github.com/kardianos/govendor:$PATH" make builder all
```

I was unable to get all of the tests to pass as I was unable to run the command as sudo, so the tests didn't pass.  However, after compiling the source I used the same trick to run `make standalone-test` and it ran - but fails intermittently.

**Comment by angelbarrera92** [comment]
I try both alternatives. Both on máster branch :(

**Comment by sargun** [comment]
For now, can you use the package that's built here: https://circleci.com/gh/Netflix/titus-executor/420#artifacts/containers/0

**Comment by sargun** [comment]
Let me know if any of this helps:
https://github.com/Netflix/titus-executor/pull/97

**Comment by sargun** [comment]
Just try running:
"make build-standalone"

**Comment by angelbarrera92** [comment]
new error :(
```
sudo -E PATH=${PATH} make build-standalone
git submodule update --init --recursive
hack/builder/titus-executor-builder.sh
~/go/src/github.com/Netflix/titus-executor ~/go/src/github.com/Netflix/titus-executor
Number of parallel builds: 3

-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-launchguard-server
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-reaper
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-vpc-tool
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-standalone
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-vpc-tool
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-darion
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-executor
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-launchguard-server
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-metadata-service
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-reaper
-->    darwin/amd64: github.com/Netflix/titus-executor/cmd/titus-standalone
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-darion
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-metadata-service
-->     linux/amd64: github.com/Netflix/titus-executor/cmd/titus-executor
make[1]: se entra en el directorio '/home/angel/go/src/github.com/Netflix/titus-executor/mount'
gcc -D_GNU_SOURCE=1 -std=gnu11 -Wall -Werror -static -g -o titus-mount mount.c
/usr/bin/ld: no se puede encontrar -lc
collect2: error: ld devolvió el estado de salida 1
make[1]: *** [Makefile:2: titus-mount] Error 1
make[1]: se sale del directorio '/home/angel/go/src/github.com/Netflix/titus-executor/mount'
make: *** [Makefile:46: build-standalone] Error 2
```

**Comment by sargun** [comment]
Can you translate this from Spanish:


/usr/bin/ld: no se puede encontrar -lc
collect2: error: ld devolvió el estado de salida 1


You might need to install libc-dev


Sent from my iPhone

On May 5, 2018, at 12:02, Ángel Barrera <notifications@github.com> wrote:

/usr/bin/ld: no se puede encontrar -lc collect2: error: ld devolvió el
estado de salida 1

**Comment by sargun** [comment]
@angelbarrera92 
Do you want to close this issue, or add instructions on how you got this to build?
